version: '3'

services:
  simple-rpg-slope:
    image: simple-rpg-slope:1.0.0-SNAPSHOT
    restart: always
    ports:
      - "8080:8080"

  simple-rpg-ski-resort:
    image: simple-rpg-ski-resort:1.0.0-SNAPSHOT
    restart: always
    environment:
      RPG_CHARACTER_URL: "http://simple-rpg-ski-resort:8080"

  simple-rpg-gateway:
    image: simple-rpg-gateway:1.0.0-SNAPSHOT
    restart: always
    environment:
      RPG_CHARACTER_URL: "http://simple-rpg-slope:8080"
      RPG_PROFESSION_URL: "http://simple-rpg-ski-resort:8080"
      RPG_GATEWAY_HOST: "simple-rpg-gateway:8080"

  angular-app:
    image: angular-app:1.0.0-SNAPSHOT
    restart: always
    environment:
      API_URL: http://simple-rpg-gateway:8080/api
    ports:
      - "8087:80"
