### Get all slopes

GET http://localhost:8084/api/slopes

### Get single slope

GET http://localhost:8084/api/slopes/fe5bfa50-95be-4a4e-8fe9-d8f11424e29e

### Get single slope, not existing

GET http://localhost:8084/api/slopes/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

### Get skiResort slopes

GET http://localhost:8084/api/skiResorts/2d9b1e8c-67c5-4188-a911-5f064a63d8cd/slopes

### Get skiResort slopes, not existing

GET http://localhost:8084/api/skiResorts/ac4e2683-b2ba-4695-94d9-806a97fce71e/slopes

### Create new slope

PUT http://localhost:8084/api/slopes/2d9b1e8c-67c5-4188-a911-5f064a63d8cd
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Koszalkowy 2",
  "steepness": 100,
  "skiResort": "2d9b1e8c-67c5-4188-a911-5f064a63d8cd"
}

### Delete slope.

DELETE http://localhost:8084/api/slopes/2d9b1e8c-67c5-4188-a911-5f064a63d8cd

### Update slope.

PATCH http://localhost:8084/api/slopes/8abcd369-e4d5-4ac6-b811-7d1a925c4895
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Koszalgowy",
  "steepness": 10
}

### Get all skiResorts

GET http://localhost:8084/api/skiResorts

### Get single skiResort

GET http://localhost:8084/api/skiResorts/2d9b1e8c-67c5-4188-a911-5f064a63d8cd

### Get single skiResort, not existing

GET http://localhost:8084/api/skiResorts/ac4e2683-b2ba-4695-94d9-806a97fce722

### Delete skiResort

DELETE http://localhost:8084/api/skiResorts/2d9b1e8c-67c5-4188-a911-5f064a63d8cd